### PR TITLE
README.md: Correct some statements about FreedesktopSDK

### PR DESCRIPTION
**Pull request by jjardon**
Hi!

One of the freedesktop-sdk maintainers here. We were quite excited to see you give buildstream/freedesktop-sdk a try in your article about build systems ( https://engineering.roku.com/you-need-a-build-system ) . Thanks for give us a try!

Still, we found some inaccuracies in the text, so we would like to correct them if you do not mind. Here a proposed PR

Thanks!

### CODE REVIEW

**Comment by staehle** [comment]
Hi Javier! Thanks for submitting this! I have a couple questions if you don't mind.

> FreedesktopSDK strives to build their outputs out of minimal binary seed instead of basing on inputs from distros

I feel like this applies to BuildStream itself, and not necessarily FreedesktopSDK?  Every BuildStream element is built hermetically, as far as I can tell, right?  Like I'm doing that here without FDSDK

Otherwise yes, for everything else thank you for the corrections. My original description was too simplistic

The remainder I would like to condense into a shorter description, however.  Would the following be acceptable?  Starting from your edit:

```diff
--- a/README.md
+++ b/README.md
@@ -14,7 +14,7 @@ 
 
 This BuildStream 2 project is quite different in comparison to other BuildStream projects.
 
-For example, FreedesktopSDK strives to build their outputs out of minimal binary seed instead of basing on inputs from distros. It also cross-compiles as little as possible (It cross-compiles its compilers, everything after is native build). FreedesktopSDK also facilitate producing reproducible natively build outputs for wide ranges of target architectures; some examples of those outputs are OS images, VMs, ICO/docker images or flatpak runtimes. If getting and architecture different from yous host is needed, that can be achieved with, for example, [Remote Execution](https://github.com/bazelbuild/remote-apis).
+For example, FreedesktopSDK specializes in providing natively built outputs of OS images, VMs, ICO/Docker images, and/or Flatpak runtimes while cross-compiling as little as possible. Targetting architectures outside of native builds has a different focus with utilizing [Remote Execution](https://github.com/bazelbuild/remote-apis).

```

Thanks for your time!

**Comment by jjardon** [comment]
Hey @staehle !

Sorry for the late reply

> I feel like this applies to BuildStream itself, and not necessarily FreedesktopSDK? Every BuildStream element is built hermetically, as far as I can tell, right? Like I'm doing that here without FDSDK

Correct, but exactly because is built hermetically the sandbox is empty

Then is decission of each buildstream project to what to use as "initial seed". You could use a tarball.from other distro but fdsdk uses a previous version of itself (and recently not even that as we build from the minimal binary possible, see https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/340 )

About your proposed change:

> +For example, FreedesktopSDK specializes in providing natively built outputs of OS images, VMs, ICO/Docker images, and/or Flatpak runtimes while cross-compiling as little as possible. Targetting architectures outside of native builds has a different focus with utilizing [Remote Execution](https://github.com/bazelbuild/remote-apis).

It looks good but I'd would change it to:
+For example, FreedesktopSDK specializes in providing natively built outputs of OS images, VMs, ICO/Docker images, and/or Flatpak runtimes while cross-compiling as little as possible. Targetting architectures outside of native builds can be done utilizing [Remote Execution](https://github.com/bazelbuild/remote-apis) or QEMU. Or you can use the freedesktop-sdk bootstrap compilers (which support crosscompilation) to build your own system

**Comment by staehle** [comment]
Perfect, thanks @jjardon !

**Comment by jjardon** [comment]
Hey @staehle !

Thanks for accepting the PR! :)

Would the article at https://engineering.roku.com/you-need-a-build-system automatically update after this merge?

**Comment by staehle** [comment]
Oh hey @jjardon , this evaluation repo is different than the article (my personal copy is here https://github.com/staehle/you-need-a-build-system ), but good point, some corrections are probably needed there as well.  I will get in contact with the blog publisher here at Roku to get that done.  I'll ping you when that's complete.  Thanks!

**Pull request merged**
